<?php

/**
 * @author Marc MOREAU <moreau.marc.web@gmail.com>
 * @license https://github.com/MockingMagician/coinbase-pro-sdk/blob/master/LICENSE.md MIT
 * @link https://github.com/MockingMagician/coinbase-pro-sdk/blob/master/README.md
 */

namespace MockingMagician\CoinbaseProSdk\Tests\Exp;

use Amp\Coroutine;
use function Amp\Promise\wait;
use function Amp\Websocket\Client\connect;
use Amp\Websocket\Client\Connection;
use Composer\InstalledVersions;
use MockingMagician\CoinbaseProSdk\Functional\Misc\Json;
use MockingMagician\CoinbaseProSdk\Functional\Websocket\Message\UnknownMessage;
use MockingMagician\CoinbaseProSdk\Functional\Websocket\MessageHandler;
use PHPUnit\Framework\TestCase;

/**
 * @internal
 */
class WSSimpleClientExpTest extends TestCase
{
    /**
     * @var WSSimpleClient
     */
    private $coinbaseSocket;
    /**
     * @var string
     */
    private $subscriber;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->subscriber = <<<'DOC'
{
    "type": "subscribe",
    "product_ids": [
        "XLM-EUR"
    ],
    "channels": [
        "level2",
        "heartbeat",
        "status",
        "ticker",
        "user",
        "match",
        "full"
    ]
}
DOC;
    }

    public function testConnection()
    {
//        dump(InstalledVersions::getReference('amphp/websocket-client'));die;
        /** @var Coroutine $connection */
        $connection = connect('wss://ws-feed.pro.coinbase.com');
        $connection = wait($connection);
        // @var Connection $connection
        wait($connection->send($this->subscriber));
        $i = 0;
        while (++$i < 5000) {
            dump($i);
            $message = wait($connection->receive());
            $payload = wait($message->buffer());
            $message = MessageHandler::handle(Json::decode($payload, true));
            if ($message instanceof UnknownMessage) {
//                dump($message->getPayload());
                dump($message);
//                die;
            }
            usleep(1000);
        }
        $connection->close();
    }
}
