<?php

namespace MockingMagician\CoinbaseProSdk\Tests\Exp;

use Amp\Coroutine;
use Amp\Websocket\Client\Connection;
use Composer\InstalledVersions;
use MockingMagician\CoinbaseProSdk\Functional\Misc\Json;
use MockingMagician\CoinbaseProSdk\Functional\Websocket\Message\AbstractMessage;
use MockingMagician\CoinbaseProSdk\Functional\Websocket\Message\StatusMessage;
use MockingMagician\CoinbaseProSdk\Functional\Websocket\Message\SubscriptionsMessage;
use MockingMagician\CoinbaseProSdk\Functional\Websocket\Message\UnknownMessage;
use MockingMagician\CoinbaseProSdk\Functional\Websocket\MessageHandler;
use PHPUnit\Framework\TestCase;
use function Amp\Promise\wait;
use function Amp\Websocket\Client\connect;

class WSSimpleClientExpTest extends TestCase
{
    /**
     * @var WSSimpleClient
     */
    private $coinbaseSocket;
    /**
     * @var string
     */
    private $subscriber;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->subscriber = <<<DOC
{
    "type": "subscribe",
    "product_ids": [
        "XLM-EUR"
    ],
    "channels": [
        "level2",
        "heartbeat",
        "status",
        "ticker",
        "user",
        "match",
        "full"
    ]
}
DOC;
    }

    public function testConnection()
    {
//        dump(InstalledVersions::getReference('amphp/websocket-client'));die;
        /** @var Coroutine $connection */
        $connection = connect('wss://ws-feed.pro.coinbase.com');
        $connection = wait($connection);
        /** @var Connection $connection */
        wait($connection->send($this->subscriber));
        $i = 0;
        while (++$i < 50) {
            $message = wait($connection->receive());
            $payload = wait($message->buffer());
            $message = MessageHandler::handle(Json::decode($payload, true));
            if ($message instanceof StatusMessage) {
                dump($message->getPayload()['currencies'][0]['details']); die;
            }
            usleep(10000);
        }
        $connection->close();
    }
}
