name: Testing suite

on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master
            - dev

jobs:
    test-job:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                php-versions: ['7.1']
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, zip
#                  ini-values: post_max_size=256M, short_open_tag=On
#                  coverage: xdebug
#                  tools: php-cs-fixer, phpunit
            - name: Check php version
              run: php --version
            - name: Check envs
              run: php -r 'var_dump([$_ENV, $_SERVER]);'
              env:
                  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
                  API_KEY: ${{ secrets.API_KEY }}
                  API_PASSPHRASE: ${{ secrets.API_PASSPHRASE }}
                  API_SECRET: ${{ secrets.API_SECRET }}
#            - name: Composer install
#              run: rm composer.lock && composer install
#            - name: Run tests
#              run: make tests


