name: Testing suite

on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master

jobs:
    functional-tests-on-each-php-version:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                php-versions: ['7.4']
        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, intl, zip
            - name: Composer install
              run: rm composer.lock && composer install
            - name: PHP version
              run: php --version
            - name: Run phpstan
              run: make phpstan
            - name: Run tests
              run: make tests
              env:
                  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
                  API_KEY: ${{ secrets.API_KEY }}
                  API_PASSPHRASE: ${{ secrets.API_PASSPHRASE }}
                  API_SECRET: ${{ secrets.API_SECRET }}
