name: Testing suite

on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master
            - dev

jobs:
    test-job:
        runs-on: 'ubuntu-latest'
        defaults:
            run:
                shell: bash
                working-directory: ./
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: 'ls_la'
              run: ls -la
            - name: Composer install
              run: composer install
            - name: Run php-cs
              run: make phpcs-dry-run
