name: Testing suite

on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master
            - dev

jobs:
    test-job:
        runs-on: 'ubuntu-latest'
        steps:
            -   id: 'run_composer'
                run: composer install
            -   id: 'run_php_cs'
                run: make phpcs-dry-run
