name: Testing suite

on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master
            - dev

jobs:
    test-job:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                php-versions: [7.1, 7.2, 7.3, 7.4]
        name: Tests with PHP ${{ matrix.php-versions }} on ${{ matrix.os }}
        defaults:
            run:
                shell: bash
                working-directory: ./
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Check php version
              run: php --version
            - name: Composer install
              run: composer install
            - name: Run php-cs
              run: make phpcs-dry-run
